version: '3'
services:
  backend:
    container_name: app
    build:
      context: ../.
      dockerfile: Docker/django/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "../app:/usr/src/app/"
    depends_on:
      - db
  db:
    container_name: pgsql
    build:
      context: ../.
      dockerfile: Docker/db/pgsql-10/Dockerfile
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: test
  frontend:
    tty: true
    container_name: client
    build:
      context: ../.
      dockerfile: Docker/client/Dockerfile
    command: npm run serve
    ports:
      - "8080:8080"
    volumes:
      - "../app:/usr/src/app/"
      - "../app/client:/usr/src/app/client/"
      - "usr/src/app/client/node_modules/"